### ISSUE TITLE
400 Response Trying to get artifact

### ISSUE THREAD

**Issue by brenkehoe** [BrandonBoone/npm-audit-widget#13]
Calls to the following url fail with 400 error and no widget data is shown:
https://XXXXXXXX.visualstudio.com/XXXXXX-a3e9-4fcc-b823-4ab3e104baad/_apis/build/builds/21836/artifacts?artifactName=audit_results

I have checked the build and it has the correct artifact with the correct name

**Comment by BrandonBoone** [comment]
Interesting, the request looks correct and nearly identical to what I'm seeing on Azure DevOps.

https://dev.azure.com/npmAuditWidget/XXXXXXXX-9f5e-4907-bbdb-6f102d42f4b5/_apis/build/builds/15/artifacts?artifactName=audit_results

The only major differences I see are the visualstudio.com domain and project name.
`https://dev.azure.com/npmAuditWidget`
`https://XXXXXXXX.visualstudio.com`

Is visualstudio.com the original Visual Studio Team Services (hosted TFS) domain. _I googled around, but everything VSTS related points me back to Azure DevOps._

Can you screenshot the build step config and the resulting artifact?

**Comment by BrandonBoone** [comment]
When I checked the URL, I pulled the request for the artifact from the HTTP traffic on dashboard page (via [fiddler](https://www.telerik.com/fiddler)). I never bothered to notice that visualstudio.com is still hosting the Azure DevOps front end. Sorry for the confusion.
